name: 'skip'
description: 'skips'
author: 'softprops'
env:
  'GITHUB_TOKEN': 'As provided by Github Actions'
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  color: 'green'
  icon: 'fast-forward'