name: Main
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./github/actions/skip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "doing stuff"
